### PR TITLE
Version 0.9.2

### PR DESCRIPTION
**Pull request by SirkoVZ**
I'm not sure about all the .idea files, are they really necessary?

### CODE REVIEW

**Comment by SirkoVZ** [comment]
...and the gradle files...?
...necessary?

**Comment by l3d00m** [comment]
I'll look into ignoring some more files / fixing some files

**Comment by l3d00m** [comment]
I've removed some more of the specific `.idea` files I missed before by adding

```
.idea/markdown-navigator
.idea/markdown-navigator.xml
projectFilesBackup
```

to my gitignore and removing them from git (not from your system) with 

```
git rm -r --cached .idea/markdown-navigator
git rm -r --cached .idea/markdown-navigator.xml
git rm -r --cached projectFilesBackup
```

It is quite common to keep the `gradle` files as you can see in other big android projects e.g. [1](https://github.com/Blankj/AndroidUtilCode) [2](https://github.com/Tencent/tinker) [3](https://github.com/android10/Android-CleanArchitecture). They are not user specific and have to get generated by Android Studio otherwise. The inspection settings are recommended to keep as they should be the same for everyone at the project.

Btw: Are you German? And is there a better way to reach you than through github or the mailing list?

Sorry for the troubles

**Comment by SirkoVZ** [comment]
Ja, per mail, z.B: mail_ist@nurfuerspam.de

**Pull request merged**
